server:
  port: 9999
  servlet:
    context-path: /job
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sonnx-dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
      username: root
      password: v5zhu0911
      tomcat:
        initial-size: 20
        min-idle: 20
        max-active: 50
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis-sql-plugin:
  enable: true
  outer-log4j-control: false
  show-connection-info: false

quartz-cluster:
  schduler:
    instance-name: springboot-vue-quartz
    instance-id: AUTO
    skip-update-check: true
    jmx-export: true
  job-store:
    clazz: org.quartz.impl.jdbcjobstore.JobStoreTX
    driver-delegate-class: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    data-source: myDS
    table-prefix: qrtz_
    cluster: true
    cluster-checkin-interval: 20000
    max-misfires-to-handle-at-a-time: 1
    misfire-threshold: 120000
    tx-isolation-level-serializable: true
    select-with-lock-sql: SELECT * FROM {0}LOCKS WHERE LOCK_NAME = ? FOR UPDATE
  thread-pool:
    clazz: org.quartz.simpl.SimpleThreadPool
    thread-count: 10
    thread-priority: 5
    threads-inherit-context-class-loader-of-initializing-thread: true
  data-source:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.28.236:3306/sonnx-dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    user: root
    password: v5zhu0911
    max-connections: 50
  plugin:
    trigg-history-class: org.quartz.plugins.history.LoggingJobHistoryPlugin
    shutdownhook-class: org.quartz.plugins.management.ShutdownHookPlugin
    shutdownhook-clean-shutdown: true